#############################################################################
# Makefile for building: extviewer
# Generated by qmake (2.01a) (Qt 4.8.6) on: Sat Nov 28 05:14:09 2015
# Project:  extviewer.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile extviewer.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-filesysascii \
		sub-libextviewer \
		sub-viewer-displaysettingswidget \
		sub-viewer-extconstantlistwidget \
		sub-viewer-extensionlistwidget \
		sub-viewer-extfunctionlistwidget \
		sub-viewer-pixelformatwidget \
		sub-viewer-webpagelistwidget \
		sub-viewer

filesysascii//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) filesysascii/ || $(MKDIR) filesysascii/ 
	cd filesysascii/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/filesysascii/filesysascii.pro -o $(MAKEFILE)
sub-filesysascii-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) filesysascii/ || $(MKDIR) filesysascii/ 
	cd filesysascii/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/filesysascii/filesysascii.pro -o $(MAKEFILE)
sub-filesysascii: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE)
sub-filesysascii-make_default: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) 
sub-filesysascii-make_first: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) first
sub-filesysascii-all: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) all
sub-filesysascii-clean: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) clean
sub-filesysascii-distclean: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) distclean
sub-filesysascii-install_subtargets: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) install
sub-filesysascii-uninstall_subtargets: filesysascii//$(MAKEFILE) FORCE
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) uninstall
libextviewer//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) libextviewer/ || $(MKDIR) libextviewer/ 
	cd libextviewer/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/libextviewer/libextviewer.pro -o $(MAKEFILE)
sub-libextviewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) libextviewer/ || $(MKDIR) libextviewer/ 
	cd libextviewer/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/libextviewer/libextviewer.pro -o $(MAKEFILE)
sub-libextviewer: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE)
sub-libextviewer-make_default: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) 
sub-libextviewer-make_first: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) first
sub-libextviewer-all: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) all
sub-libextviewer-clean: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-libextviewer-distclean: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-libextviewer-install_subtargets: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) install
sub-libextviewer-uninstall_subtargets: libextviewer//$(MAKEFILE) FORCE
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/displaysettingswidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/displaysettingswidget/ || $(MKDIR) viewer/displaysettingswidget/ 
	cd viewer/displaysettingswidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/displaysettingswidget/displaysettingswidget.pro -o $(MAKEFILE)
sub-viewer-displaysettingswidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/displaysettingswidget/ || $(MKDIR) viewer/displaysettingswidget/ 
	cd viewer/displaysettingswidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/displaysettingswidget/displaysettingswidget.pro -o $(MAKEFILE)
sub-viewer-displaysettingswidget: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-displaysettingswidget-make_default: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-displaysettingswidget-make_first: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-displaysettingswidget-all: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-displaysettingswidget-clean: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-displaysettingswidget-distclean: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-displaysettingswidget-install_subtargets: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-displaysettingswidget-uninstall_subtargets: viewer/displaysettingswidget//$(MAKEFILE) FORCE
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/extconstantlistwidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/extconstantlistwidget/ || $(MKDIR) viewer/extconstantlistwidget/ 
	cd viewer/extconstantlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extconstantlistwidget/extconstantlistwidget.pro -o $(MAKEFILE)
sub-viewer-extconstantlistwidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/extconstantlistwidget/ || $(MKDIR) viewer/extconstantlistwidget/ 
	cd viewer/extconstantlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extconstantlistwidget/extconstantlistwidget.pro -o $(MAKEFILE)
sub-viewer-extconstantlistwidget: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-extconstantlistwidget-make_default: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-extconstantlistwidget-make_first: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-extconstantlistwidget-all: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-extconstantlistwidget-clean: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-extconstantlistwidget-distclean: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-extconstantlistwidget-install_subtargets: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-extconstantlistwidget-uninstall_subtargets: viewer/extconstantlistwidget//$(MAKEFILE) FORCE
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/extensionlistwidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/extensionlistwidget/ || $(MKDIR) viewer/extensionlistwidget/ 
	cd viewer/extensionlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extensionlistwidget/extensionlistwidget.pro -o $(MAKEFILE)
sub-viewer-extensionlistwidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/extensionlistwidget/ || $(MKDIR) viewer/extensionlistwidget/ 
	cd viewer/extensionlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extensionlistwidget/extensionlistwidget.pro -o $(MAKEFILE)
sub-viewer-extensionlistwidget: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-extensionlistwidget-make_default: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-extensionlistwidget-make_first: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-extensionlistwidget-all: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-extensionlistwidget-clean: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-extensionlistwidget-distclean: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-extensionlistwidget-install_subtargets: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-extensionlistwidget-uninstall_subtargets: viewer/extensionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/extfunctionlistwidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/extfunctionlistwidget/ || $(MKDIR) viewer/extfunctionlistwidget/ 
	cd viewer/extfunctionlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extfunctionlistwidget/extfunctionlistwidget.pro -o $(MAKEFILE)
sub-viewer-extfunctionlistwidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/extfunctionlistwidget/ || $(MKDIR) viewer/extfunctionlistwidget/ 
	cd viewer/extfunctionlistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/extfunctionlistwidget/extfunctionlistwidget.pro -o $(MAKEFILE)
sub-viewer-extfunctionlistwidget: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-extfunctionlistwidget-make_default: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-extfunctionlistwidget-make_first: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-extfunctionlistwidget-all: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-extfunctionlistwidget-clean: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-extfunctionlistwidget-distclean: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-extfunctionlistwidget-install_subtargets: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-extfunctionlistwidget-uninstall_subtargets: viewer/extfunctionlistwidget//$(MAKEFILE) FORCE
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/pixelformatwidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/pixelformatwidget/ || $(MKDIR) viewer/pixelformatwidget/ 
	cd viewer/pixelformatwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/pixelformatwidget/pixelformatwidget.pro -o $(MAKEFILE)
sub-viewer-pixelformatwidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/pixelformatwidget/ || $(MKDIR) viewer/pixelformatwidget/ 
	cd viewer/pixelformatwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/pixelformatwidget/pixelformatwidget.pro -o $(MAKEFILE)
sub-viewer-pixelformatwidget: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-pixelformatwidget-make_default: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-pixelformatwidget-make_first: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-pixelformatwidget-all: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-pixelformatwidget-clean: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-pixelformatwidget-distclean: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-pixelformatwidget-install_subtargets: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-pixelformatwidget-uninstall_subtargets: viewer/pixelformatwidget//$(MAKEFILE) FORCE
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer/webpagelistwidget//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/webpagelistwidget/ || $(MKDIR) viewer/webpagelistwidget/ 
	cd viewer/webpagelistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/webpagelistwidget/webpagelistwidget.pro -o $(MAKEFILE)
sub-viewer-webpagelistwidget-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/webpagelistwidget/ || $(MKDIR) viewer/webpagelistwidget/ 
	cd viewer/webpagelistwidget/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/webpagelistwidget/webpagelistwidget.pro -o $(MAKEFILE)
sub-viewer-webpagelistwidget: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-webpagelistwidget-make_default: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-webpagelistwidget-make_first: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-webpagelistwidget-all: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-webpagelistwidget-clean: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-webpagelistwidget-distclean: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-webpagelistwidget-install_subtargets: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-webpagelistwidget-uninstall_subtargets: viewer/webpagelistwidget//$(MAKEFILE) FORCE
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) uninstall
viewer//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) viewer/ || $(MKDIR) viewer/ 
	cd viewer/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/viewer.pro -o $(MAKEFILE)
sub-viewer-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) viewer/ || $(MKDIR) viewer/ 
	cd viewer/ && $(QMAKE) /home/msar/Desktop/demos/openglextensionviewer-code/viewer/viewer.pro -o $(MAKEFILE)
sub-viewer: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE)
sub-viewer-make_default: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) 
sub-viewer-make_first: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) first
sub-viewer-all: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) all
sub-viewer-clean: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) clean
sub-viewer-distclean: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) distclean
sub-viewer-install_subtargets: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) install
sub-viewer-uninstall_subtargets: viewer//$(MAKEFILE) FORCE
	cd viewer/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: extviewer.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile extviewer.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile extviewer.pro

qmake_all: sub-filesysascii-qmake_all sub-libextviewer-qmake_all sub-viewer-displaysettingswidget-qmake_all sub-viewer-extconstantlistwidget-qmake_all sub-viewer-extensionlistwidget-qmake_all sub-viewer-extfunctionlistwidget-qmake_all sub-viewer-pixelformatwidget-qmake_all sub-viewer-webpagelistwidget-qmake_all sub-viewer-qmake_all FORCE

make_default: sub-filesysascii-make_default sub-libextviewer-make_default sub-viewer-displaysettingswidget-make_default sub-viewer-extconstantlistwidget-make_default sub-viewer-extensionlistwidget-make_default sub-viewer-extfunctionlistwidget-make_default sub-viewer-pixelformatwidget-make_default sub-viewer-webpagelistwidget-make_default sub-viewer-make_default FORCE
make_first: sub-filesysascii-make_first sub-libextviewer-make_first sub-viewer-displaysettingswidget-make_first sub-viewer-extconstantlistwidget-make_first sub-viewer-extensionlistwidget-make_first sub-viewer-extfunctionlistwidget-make_first sub-viewer-pixelformatwidget-make_first sub-viewer-webpagelistwidget-make_first sub-viewer-make_first FORCE
all: sub-filesysascii-all sub-libextviewer-all sub-viewer-displaysettingswidget-all sub-viewer-extconstantlistwidget-all sub-viewer-extensionlistwidget-all sub-viewer-extfunctionlistwidget-all sub-viewer-pixelformatwidget-all sub-viewer-webpagelistwidget-all sub-viewer-all FORCE
clean: sub-filesysascii-clean sub-libextviewer-clean sub-viewer-displaysettingswidget-clean sub-viewer-extconstantlistwidget-clean sub-viewer-extensionlistwidget-clean sub-viewer-extfunctionlistwidget-clean sub-viewer-pixelformatwidget-clean sub-viewer-webpagelistwidget-clean sub-viewer-clean FORCE
distclean: sub-filesysascii-distclean sub-libextviewer-distclean sub-viewer-displaysettingswidget-distclean sub-viewer-extconstantlistwidget-distclean sub-viewer-extensionlistwidget-distclean sub-viewer-extfunctionlistwidget-distclean sub-viewer-pixelformatwidget-distclean sub-viewer-webpagelistwidget-distclean sub-viewer-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-filesysascii-install_subtargets sub-libextviewer-install_subtargets sub-viewer-displaysettingswidget-install_subtargets sub-viewer-extconstantlistwidget-install_subtargets sub-viewer-extensionlistwidget-install_subtargets sub-viewer-extfunctionlistwidget-install_subtargets sub-viewer-pixelformatwidget-install_subtargets sub-viewer-webpagelistwidget-install_subtargets sub-viewer-install_subtargets FORCE
uninstall_subtargets: sub-filesysascii-uninstall_subtargets sub-libextviewer-uninstall_subtargets sub-viewer-displaysettingswidget-uninstall_subtargets sub-viewer-extconstantlistwidget-uninstall_subtargets sub-viewer-extensionlistwidget-uninstall_subtargets sub-viewer-extfunctionlistwidget-uninstall_subtargets sub-viewer-pixelformatwidget-uninstall_subtargets sub-viewer-webpagelistwidget-uninstall_subtargets sub-viewer-uninstall_subtargets FORCE

sub-filesysascii-check: filesysascii/$(MAKEFILE)
	cd filesysascii/ && $(MAKE) -f $(MAKEFILE) check
sub-libextviewer-check: libextviewer/$(MAKEFILE)
	cd libextviewer/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-displaysettingswidget-check: viewer/displaysettingswidget/$(MAKEFILE)
	cd viewer/displaysettingswidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-extconstantlistwidget-check: viewer/extconstantlistwidget/$(MAKEFILE)
	cd viewer/extconstantlistwidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-extensionlistwidget-check: viewer/extensionlistwidget/$(MAKEFILE)
	cd viewer/extensionlistwidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-extfunctionlistwidget-check: viewer/extfunctionlistwidget/$(MAKEFILE)
	cd viewer/extfunctionlistwidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-pixelformatwidget-check: viewer/pixelformatwidget/$(MAKEFILE)
	cd viewer/pixelformatwidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-webpagelistwidget-check: viewer/webpagelistwidget/$(MAKEFILE)
	cd viewer/webpagelistwidget/ && $(MAKE) -f $(MAKEFILE) check
sub-viewer-check: viewer/$(MAKEFILE)
	cd viewer/ && $(MAKE) -f $(MAKEFILE) check
check: sub-filesysascii-check sub-libextviewer-check sub-viewer-displaysettingswidget-check sub-viewer-extconstantlistwidget-check sub-viewer-extensionlistwidget-check sub-viewer-extfunctionlistwidget-check sub-viewer-pixelformatwidget-check sub-viewer-webpagelistwidget-check sub-viewer-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

